//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bron
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bron()
        {
            this.ConfirmedBooking = new HashSet<ConfirmedBooking>();
        }
    
        public int BronID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime BookingDate { get; set; }
        public System.TimeSpan BookingTime { get; set; }
        public int GuestsCount { get; set; }
        public int StolID { get; set; }
        public string Status { get; set; }
    
        public virtual Stol Stol { get; set; }
        public virtual Waiter Waiter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfirmedBooking> ConfirmedBooking { get; set; }
    }
}
