//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfirmedBooking
    {
        public int ConfirmedBookingID { get; set; }
        public int AdminID { get; set; }
        public int WaiterID { get; set; }
        public int BronID { get; set; }
        public System.DateTime ConfirmationDate { get; set; }
    
        public virtual Administrator Administrator { get; set; }
        public virtual Bron Bron { get; set; }
        public virtual Waiter Waiter { get; set; }
    }
}
